# Generated by Django 5.2.4 on 2025-07-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('extract', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
